### PR TITLE
Move the autocommand creation from the Lua module to a plugin

### PR DESCRIPTION
**Pull request by bmrips**
See the commit for details.

### CODE REVIEW

**Comment by jghauser** [comment]
Hey! I'm very sorry, this has completely escaped my attention! Why do you think these changes are advantageous? I generally prefer to keep things lua-only and quite like the rather common standard where requiring a lua plugin is done explicitly. I'm also thinking to convert the autocmds once the relevant lua api is implemented in neovim (so creating a .vim file for that now seems a bit of waste).

**Comment by bmrips** [comment]
No problem, it's not urgent. I also prefer to use the Lua api. My reason for this PR is, that there is no api for autocommands (like you mentioned) and there is no need to load the whole Lua module on initialisation. Furthermore, in my opinion, the pattern to require plugins explicitly is only beneficial for mappings and settings, i.e. behaviour that some want to configure.

But as you said, it might be rather an opinion than an undisputable improvement. I would not mind if you just close it.

**Comment by jghauser** [comment]
Thanks for the explanation (and for writing this PR)! I'll keep it as it is for now as it doesn't really impact how things work very much and will make it easier to switch to the lua api once that's ready.

**Comment by gpanders** [comment]
Note that you can use Lua for plugin files, so you can make this a plugin file (which will cause it to run automatically, without requiring your users to use `require('mkdir')`) and still use Lua.

**Comment by jghauser** [comment]
You're right about that! I don't know why I didn't consider it then. I've also come to see that my insistence on explicitly calling the setup function is a little silly with a plugin such as this one. Changing this now!

**Pull request closed without merging**
